name: Sync to Hugging Face Spaces

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: true

      - name: Reset Git History for Clean Push
        run: |
          # Remove existing Git history to prevent uploading historical heavy models
          rm -rf .git

          # Initialize fresh repository
          git init -b main
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Initialize LFS
          git lfs install

          # Prepend Hugging Face YAML metadata to README.md on the fly
          cat << 'EOF' > temp_readme
          ---
          title: Real-Time Phishing Detection System
          emoji: 🛡️
          colorFrom: red
          colorTo: blue
          sdk: docker
          app_port: 7860
          ---

          EOF
          cat README.md >> temp_readme
          mv temp_readme README.md

          # Stage and commit only current files (ignores what is in .gitignore)
          git add .
          git commit -m "deploy: clean sync with lightweight models"

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/lewischu/phishing-detection-api
          git push --force hf main:refs/heads/main
